description: "Off Topic"
publisher: "Various"
keywords: "Off Topic"
title: "Off Topic"

name: "Off Topic"

email: "email@razox.com"

permalink: /:categories/:title/

paginate: 3
paginate_path: "/jokes/:num/"

plugins:
  - jekyll-redirect-from
