description: "Off Topic"
publisher: "Various"
keywords: "Off Topic"
title: "Off Topic"

name: "Off Topic"

email: "email@razox.com"

permalink: /:categories/:title/

paginate: 3
paginate_path: "/jokes/:num/"

plugins:
  - jekyll-redirect-from

collections:
  jokes:
    output: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
      type: "jokes"
    values:
      layout: "joke"
      title: "Jokes"
      subtitle: "from&nbsp;the&nbsp;Vortex"
      lead: "No&nbsp;Of&nbsp;fence"
